//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Resources;

[assembly: AssemblyVersion("1.0.3.0")]
[assembly: AssemblyFileVersion("1.0.3.50843")]
[assembly: AssemblyInformationalVersion("1.0.3+9bc6084653")]
[assembly: ComVisible(true)]

[assembly: InternalsVisibleTo("Float.Core.Tests")]

// Custom Attributes
[assembly: NeutralResourcesLanguage("en")]
