name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Retore Workload
        run: dotnet workload restore
      - name: Restore dependencies
        run: dotnet restore
      - name: .NET project version updater
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          files: |
            "Float.Core/Float.Core.csproj", "**/*.nuspec", "**/AssemblyInfo.cs"
          version: ${{ github.event.release.name }}
      - name: Build Library
        run: dotnet build ./Float.Core/Float.Core.csproj --configuration Release --no-restore
      - name: Pack and Upload
        run: dotnet pack --configuration Release --no-restore
      - name: Deploy to NuGet
        env:
          FLOAT_NUGET_TOKEN: ${{ secrets.FLOAT_NUGET_TOKEN }}
        run: dotnet nuget push ./Float.Core/bin/Release/Float.Core.${{ github.event.release.name }}.nupkg --api-key "${FLOAT_NUGET_TOKEN}" --source https://api.nuget.org/v3/index.json
